version: "3.9"
services:
  scraper-proxy:
    container_name: SCRAPERPROXY_DEV
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3031:3031
    volumes:
      - .:/workspaces/scraperProxy
    env_file:
      - .devcontainer/dev.env
    working_dir: /workspaces/scraperProxy
    tty: true
    entrypoint: ["bash"]
